[connections.neon]
dialect = "postgresql"
host = "ep-falling-paper-anwys5nt-pooler.c-6.us-east-1.aws.neon.tech"
port = "5432"
database = "neondb"
username = "neondb_owner"
password = "npg_WI72rsVUkonT"